language: rust
rust:
  - 1.12.0
  - stable
  - beta
  - nightly
script:
  - cargo build --verbose
  - cargo build --verbose --features ansi_formatting
  - cargo doc
  - cargo test --verbose
  - cargo test --verbose --features ansi_formatting
  - if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then
      cargo bench --verbose;
      cargo bench --verbose --features ansi_formatting;
    fi
